import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'bn' | 'hi';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'home': 'Home',
    'wallet': 'Wallet',
    'myBets': 'My Bets',
    'profile': 'Profile',
    'live': 'Live',
    'join': 'Join',
    'joinNow': 'JOIN MATCH NOW',
    'totalPlayers': 'Total Players',
    'prizePool': 'Prize Pool',
    'entryFee': 'Entry Fee',
    'matchDetails': 'Match Details',
    'login': 'Login',
    'register': 'Register',
    'balance': 'Balance',
    'deposit': 'Deposit',
    'withdraw': 'Withdraw',
    'gamingArena': 'Gaming Arena',
    'arenaSub': 'Join matches & earn rewards',
    'active': 'Active',
    'completed': 'Completed',
    'history': 'History',
    'details': 'Details',
    'confirmEntry': 'Confirm Your Entry',
    'success': 'Success',
    'joined': 'Joined!',
    'language': 'Language',
    'selectLanguage': 'Select Language',
    'players': 'Players',
    'entry': 'Entry',
    'slotsOccupied': 'Slots Occupied',
    'capacity': 'CAPACITY',
    'fullHouse': 'FULL HOUSE',
    'joinBattleground': 'JOIN BATTLEGROUND',
    'tacticalIntel': 'Tactical Intel',
    'closesIn': 'CLOSES IN',
    'matchLive': 'MATCH LIVE - JOINED PLAYERS',
    'matchFull': 'MATCH FULL - SLOTS CLOSED',
    'soloInstruction': 'Solo Mode: 48 members total. Only 1 member per entry. When 48 slots are filled, no other members can join.',
    'duoInstruction': 'Duo/Dot Mode: 24 teams (48 players). 2 members per team. When 24 teams join, no other members can join.',
    'squadInstruction': 'Squad Mode: 12 teams (48 players). 4 members per team. When 12 teams join, no other members can join.',
    'settings': 'Settings',
    'accountSecurity': 'Account Security',
    'paymentMethods': 'Payment Methods',
    'notifications': 'Notifications',
    'languageRegion': 'Language & Region',
    'appearance': 'Appearance',
    'helpCenter': 'Help Center',
    'logout': 'Logout',
    'matchesWon': 'Matches Won',
    'matchesLost': 'Matches Lost',
    'battleBuddy': 'Battle Buddy',
    'connections': 'Connections',
    'viewAll': 'View All',
    'editProfile': 'Edit Profile',
    'fullName': 'Full Name',
    'username': 'Username',
    'updateProfile': 'UPDATE PROFILE',
    'linkedAccounts': 'My Linked Accounts',
    'linkNew': 'LINK NEW ACCOUNT',
    'selectGateway': 'Select Gateway',
    'quickAmount': 'Quick Amount',
    'customAmount': 'Custom Amount',
    'addFunds': 'ADD FUNDS NOW',
    'withdrawWinnings': 'Withdraw Winnings',
    'requestWithdrawal': 'REQUEST WITHDRAWAL',
    'recentActivity': 'Recent Activity',
    'noActivity': 'No recent activity',
    'transactionHistory': 'Transaction History',
    'userId': 'USER ID',
    'confirmSelection': 'CONFIRM SELECTION',
    'savePreferences': 'SAVE PREFERENCES',
    'startTime': 'STARTS AT'
  },
  bn: {
    'home': 'হোম',
    'wallet': 'ওয়ালেট',
    'myBets': 'আমার বাজি',
    'profile': 'প্রোফাইল',
    'live': 'লাইভ',
    'join': 'যোগ দিন',
    'joinNow': 'এখনই যোগ দিন',
    'totalPlayers': 'মোট খেলোয়াড়',
    'prizePool': 'প্রাইজ পুল',
    'entryFee': 'এন্ট্রি ফি',
    'matchDetails': 'ম্যাচের বিবরণ',
    'login': 'লগইন',
    'register': 'রেজিস্টার',
    'balance': 'ব্যালেন্স',
    'deposit': 'জমা করুন',
    'withdraw': 'উত্তোলন',
    'gamingArena': 'গেমিং এরিনা',
    'arenaSub': 'ম্যাচে যোগ দিন এবং পুরস্কার জিতুন',
    'active': 'সক্রিয়',
    'completed': 'সম্পন্ন',
    'history': 'ইতিহাস',
    'details': 'বিস্তারিত',
    'confirmEntry': 'আপনার এন্ট্রি নিশ্চিত করুন',
    'success': 'সফল',
    'joined': 'যোগদান করেছেন!',
    'language': 'ভাষা',
    'selectLanguage': 'ভাষা নির্বাচন করুন',
    'players': 'খেলোয়াড়',
    'entry': 'এন্ট্রি',
    'slotsOccupied': 'স্লট দখল করা হয়েছে',
    'capacity': 'ক্ষমতা',
    'fullHouse': 'ফুল হাউস',
    'joinBattleground': 'ব্যাটলগ্রাউন্ডে যোগ দিন',
    'tacticalIntel': 'কৌশলগত তথ্য',
    'closesIn': 'বন্ধ হবে:',
    'matchLive': 'ম্যাচ লাইভ - অংশগ্রহণকারী খেলোয়াড়',
    'matchFull': 'ম্যাচ পূর্ণ - স্লট বন্ধ',
    'soloInstruction': 'সোলো মোড: মোট ৪৮ জন সদস্য। প্রতি এন্ট্রিতে মাত্র ১ জন সদস্য। ৪৮টি স্লট পূর্ণ হলে অন্য কেউ যোগ দিতে পারবে না।',
    'duoInstruction': 'ডুও মোড: ২৪টি দল (৪৮ জন খেলোয়াড়)। প্রতি দলে ২ জন সদস্য। ২৪টি দল যোগ দিলে অন্য কেউ যোগ দিতে পারবে না।',
    'squadInstruction': 'স্কোয়াড মোড: ১২টি দল (৪৮ জন খেলোয়াড়)। প্রতি দলে ৪ জন সদস্য। ১২টি দল যোগ দিলে অন্য কেউ যোগ দিতে পারবে না।',
    'settings': 'সেটিংস',
    'accountSecurity': 'অ্যাকাউন্ট নিরাপত্তা',
    'paymentMethods': 'পেমেন্ট পদ্ধতি',
    'notifications': 'নোটিফিকেশন',
    'languageRegion': 'ভাষা ও অঞ্চল',
    'appearance': 'চেহারা',
    'helpCenter': 'হেল্প সেন্টার',
    'logout': 'লগআউট',
    'matchesWon': 'ম্যাচ জয়ী',
    'matchesLost': 'ম্যাচ পরাজিত',
    'battleBuddy': 'ব্যাটল বাডি',
    'connections': 'কানেকশন',
    'viewAll': 'সব দেখুন',
    'editProfile': 'প্রোফাইল এডিট করুন',
    'fullName': 'পুরো নাম',
    'username': 'ব্যবহারকারীর নাম',
    'updateProfile': 'প্রোফাইল আপডেট করুন',
    'linkedAccounts': 'আমার লিঙ্ক করা অ্যাকাউন্ট',
    'linkNew': 'নতুন অ্যাকাউন্ট লিঙ্ক করুন',
    'selectGateway': 'গেটওয়ে নির্বাচন করুন',
    'quickAmount': 'দ্রুত পরিমাণ',
    'customAmount': 'কাস্টম পরিমাণ',
    'addFunds': 'এখনই টাকা যোগ করুন',
    'withdrawWinnings': 'জেতা টাকা উত্তোলন',
    'requestWithdrawal': 'উত্তোলনের অনুরোধ করুন',
    'recentActivity': 'সাম্প্রতিক কার্যক্রম',
    'noActivity': 'কোন সাম্প্রতিক কার্যক্রম নেই',
    'transactionHistory': 'লেনদেনের ইতিহাস',
    'userId': 'ইউজার আইডি',
    'confirmSelection': 'নির্বাচন নিশ্চিত করুন',
    'savePreferences': 'পছন্দগুলি সংরক্ষণ করুন',
    'startTime': 'শুরু হবে'
  },
  hi: {
    'home': 'होम',
    'wallet': 'वॉलेट',
    'myBets': 'मेरी बेट्स',
    'profile': 'प्रोफाइल',
    'live': 'लाइव',
    'join': 'शामिल हों',
    'joinNow': 'अभी शामिल हों',
    'totalPlayers': 'कुल खिलाड़ी',
    'prizePool': 'प्राइज़ पूल',
    'entryFee': 'एंट्री फीस',
    'matchDetails': 'मैच विवरण',
    'login': 'लॉगिन',
    'register': 'रजिस्टर',
    'balance': 'बैलेंस',
    'deposit': 'जमा करें',
    'withdraw': 'निकासी',
    'gamingArena': 'गेमिंग एरिना',
    'arenaSub': 'मैचों में शामिल हों और पुरस्कार जीतें',
    'active': 'सक्रिय',
    'completed': 'पूरा हुआ',
    'history': 'इतिहास',
    'details': 'विवरण',
    'confirmEntry': 'अपनी प्रविष्टि की पुष्टि करें',
    'success': 'सफल',
    'joined': 'शामिल हो गए!',
    'language': 'भाषा',
    'selectLanguage': 'भाषा चुनें',
    'players': 'खिलाड़ी',
    'entry': 'एंट्री',
    'slotsOccupied': 'स्लॉट भरे हुए हैं',
    'capacity': 'क्षमता',
    'fullHouse': 'हाउस फुल',
    'joinBattleground': 'मैदान में उतरें',
    'tacticalIntel': 'रणनीतिक जानकारी',
    'closesIn': 'समाप्ति समय:',
    'matchLive': 'मैच लाइव - खिलाड़ी शामिल हैं',
    'matchFull': 'मैच फुल - स्लॉट बंद',
    'soloInstruction': 'सोलो मोड: कुल 48 सदस्य। प्रति प्रविष्टि केवल 1 सदस्य। 48 स्लॉट भरने पर कोई अन्य सदस्य शामिल नहीं हो सकता।',
    'duoInstruction': 'डुओ मोड: 24 टीमें (48 खिलाड़ी)। प्रति टीम 2 सदस्य। 24 टीमें शामिल होने पर कोई अन्य सदस्य शामिल नहीं हो सकता।',
    'squadInstruction': 'स्क्वाड मोड: 12 टीमें (48 खिलाड़ी)। प्रति टीम 4 सदस्य। 12 टीमें शामिल होने पर कोई अन्य सदस्य शामिल नहीं हो सकता।',
    'settings': 'सेटिंग्स',
    'accountSecurity': 'अकाउंट सुरक्षा',
    'paymentMethods': 'भुगतान विधियां',
    'notifications': 'नोटिफिकेशन',
    'languageRegion': 'भाषा और क्षेत्र',
    'appearance': 'रंग-रूप',
    'helpCenter': 'सहायता केंद्र',
    'logout': 'लॉगआउट',
    'matchesWon': 'मैच जीते',
    'matchesLost': 'मैच हारे',
    'battleBuddy': 'बैटल बडी',
    'connections': 'कनेक्शन',
    'viewAll': 'सभी देखें',
    'editProfile': 'प्रोफ़ाइल संपादित करें',
    'fullName': 'पूरा नाम',
    'username': 'यूज़रनेम',
    'updateProfile': 'प्रोफ़ाइल अपडेट करें',
    'linkedAccounts': 'मेरे लिंक किए गए अकाउंट',
    'linkNew': 'नया अकाउंट लिंक करें',
    'selectGateway': 'गेटवे चुनें',
    'quickAmount': 'त्वरित राशि',
    'customAmount': 'कस्टम राशि',
    'addFunds': 'अभी फंड जोड़ें',
    'withdrawWinnings': 'जीत की निकासी',
    'requestWithdrawal': 'निकासी का अनुरोध करें',
    'recentActivity': 'हाल की गतिविधि',
    'noActivity': 'कोई हाल की गतिविधि नहीं',
    'transactionHistory': 'लेनदेन का इतिहास',
    'userId': 'यूज़र आईडी',
    'confirmSelection': 'चयन की पुष्टि करें',
    'savePreferences': 'पसंद सहेजें',
    'startTime': 'शुरू होगा'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('appLanguage');
    return (saved as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('appLanguage', lang);
  };

  const t = (key: string) => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
